# Generated by Django 3.2.4 on 2021-06-18 06:05

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ismi-Familya')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefon')),
                ('subject', models.CharField(max_length=250, verbose_name='Mavzu')),
                ('message', models.TextField(verbose_name="Qo'shimcha xabar")),
            ],
            options={
                'verbose_name': 'Aloqa',
                'verbose_name_plural': 'Aloqalar',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Kurs nomi')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='*')),
                ('short_desc', models.CharField(max_length=300, verbose_name='Qisqacha info')),
                ('desc', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='course_poster/', verbose_name='Kurs rasmi kichkina')),
                ('high_image', models.ImageField(blank=True, null=True, upload_to='course_poster/', verbose_name='Kurs rasmi asosiy')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Nomi')),
                ('body', ckeditor.fields.RichTextField()),
                ('youtube_link', models.CharField(max_length=250, verbose_name='You tube link')),
                ('image', models.ImageField(upload_to='posters/', verbose_name='Rasmi')),
                ('author', models.CharField(max_length=50, verbose_name='Muallif')),
                ('published', models.DateTimeField(auto_now_add=True, verbose_name='Sanasi')),
            ],
            options={
                'verbose_name': 'Maqola',
                'verbose_name_plural': 'Maqolalar',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('keladi', 'Keladi'), ('kemedi', 'Kelmaydi'), ('aniqmas', 'Aniq emas')], max_length=50, verbose_name='Status')),
                ('comment', models.TextField(verbose_name="Sababi/Qo'shimcha xabar")),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ismi-Familya')),
                ('age', models.CharField(max_length=50, verbose_name='Yosh')),
                ('phone', models.CharField(max_length=15, verbose_name='Telefon')),
                ('course', models.CharField(choices=[('lego', 'Bolalar uchun dasturlash'), ('arduino', 'Arduino'), ('web', 'Web dasturlash'), ('grafika', 'Grafik dizayn'), ('computer', 'Computer Science')], max_length=50, verbose_name='Kurs')),
                ('message', models.TextField(verbose_name="Qo'shimcha xabar")),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Sanasi')),
                ('inner', models.BooleanField(blank=True, default=False, null=True, verbose_name='Keladi')),
                ('outer', models.BooleanField(blank=True, default=False, null=True, verbose_name='Kemedi')),
                ('unknown', models.BooleanField(blank=True, default=False, null=True, verbose_name='Aniq emas')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_status', to='main.status')),
            ],
            options={
                'verbose_name': "A'zo bo'lgan",
                'verbose_name_plural': "A'zo bo'lganlar",
            },
        ),
    ]
